--.Từ khóa Distinct:Loại bỏ các kết quả dữ liệu trùng nhau
--.Ví dụ: CHO BIẾT KHÓA CÁC LỚP
 -- SELECT DISTINCT KHOA
 --  FROM LOP
--.ĐỂ HIỂN THỊ CÁC CỘT CÙNG TÊN KHI LÀM VIỆC TRÊN KHI LÀM VIỆC TRÊN NHIỀU BẢNG THÌ PHẢI CHỈ RÕ CÁC CỘT CÙNG TÊN ĐÓ THUỘC BẢNG NÀO:
--<TÊN BẢNG>.<TÊN CỘT CHUNG>
--LỖI: AMBIGIOUS COLUMN NAME
--VÍ DỤ HIỂN THỊ MÃ HÀNG ,TÊN HÀNG ,SL,GIÁ HÀNG
--BẢNG MẶT HÀNG VÀ CTMH
SELECT MATHANG.MAHANG,TENHANG,CHITIETDATHANG.SOLUONG,GIABAN
   FROM MATHANG INNER JOIN CHITIETDATHANG 
   ON MATHANG.MAHANG = CHITIETDATHANG.MAHANG
   
--VÍ DỤ HIỂN THỊ MÃ HÀNG ,TÊN HÀNG ,SL,GIÁ BÁN CỦA CÁC MẶT HÀNG
SELECT MATHANG.MAHANG,MATHANG.TENHANG,MATHANG.SOLUONG,CHITIETDATHANG.GIABAN
  FROM MATHANG 
  INNER JOIN CHITIETDATHANG ON MATHANG.MAHANG = CHITIETDATHANG.MAHANG
  --VÍ DỤ 2:CHO BIẾT CÁC ĐỐI TÁC CUNG CẤP CÁC MẶT HÀNG CHO CÔNG TY
  --HIỂN THỊ : MÃ CÔNG TY,TÊN CÔNG TY, MÃ HÀNG,TÊN HÀNG

  SELECT  DISTINCT NHACUNGCAP.MACONGTY,TENCONGTY,MATHANG .MAHANG,TENHANG
      FROM MATHANG 
	  INNER JOIN NHACUNGCAP
	  ON MATHANG.MACONGTY = NHACUNGCAP.MACONGTY
	--ĐẶT LAI TÊN BẢNG
SELECT NCC.MACONGTY,TENCONGTY,MH.MAHANG,TENHANG
   FROM MATHANG AS MH 
   INNER JOIN NHACUNGCAP AS NCC
	      ON MH.MACONGTY = NCC.MACONGTY
--NỐI 3 BẢNG
--VÍ DỤ: CHO BIẾT MỖI ĐƠN ĐẶT HÀNG LÀ BAO GỒM NHỮNG MẶT HÀNG NÀO
--HIỂN THỊ: SOHOADON,NGAYGIAOHANG,MAHANG,TENHANG
--BẢNG: ĐONATHANG,CHITIETDATHANG,MATHANG
SELECT  DDH.SOHOADON,NGAYGIAOHANG,MH.MAHANG,TENHANG
   FROM DONDATHANG AS DDH
   INNER JOIN CHITIETDATHANG AS CTDH
          ON DDH.SOHOADON = CTDH.SOHOADON
   INNER JOIN MATHANG AS MH
          ON MH.MAHANG = CTDH.MAHANG
--cho biet moi nhan vien da cung cap nhung mat hang nao
--hien thi: MANHANVIEN,HO,TEN,MAHANG,TENHANG
--BANG: NHANVIEN,DONDATHANG,CHITIETDATHANG,MATHANG
SELECT NV.MANHANVIEN,HO + ' ' + TEN AS 'HO TEN',MH.MAHANG,TENHANG
   FROM NHANVIEN AS NV
   INNER JOIN DONDATHANG AS DDH
          ON NV.MANHANVIEN = DDH.MANHANVIEN
   INNER JOIN CHITIETDATHANG AS CTDH
          ON CTDH.SOHOADON = DDH.SOHOADON
   INNER JOIN MATHANG AS MH
          ON MH.MAHANG = CTDH.MAHANG
--5.5 CHO BIET MA VA TEN CUA CAC MAT HANG CO GIA LON HON 1000 VA SO LUONG HIEN IT HON 50
SELECT MAHANG,TENHANG, GIAHANG,SOLUONG
    FROM MATHANG
WHERE GIAHANG > 1000 AND
      SOLUONG < 50


