--22.Hãy cho biết mỗi khách hàng đã phải bỏ ra bao nhiêu tiền để mua mặt hàng của công ty
--Hiển thị mã khách hàng,tên công ty
SELECT KH.MAKHACHHANG,TENCONGTY,SUM(CTDH.SOLUONG * CTDH.GIABAN - CTDH.SOLUONG * CTDH.GIABAN * CTDH.MUCGIAMGIA/100) AS TONG
   FROM KHACHHANG AS KH
        INNER JOIN DONDATHANG AS DDH
	           ON KH.MAKHACHHANG = DDH.MAKHACHHANG
        INNER JOIN CHITIETDATHANG AS CTDH
	           ON DDH.SOHOADON = CTDH.SOHOADON
GROUP BY KH.MAKHACHHANG,TENCONGTY
--23 Mỗi một nhân viên của công ty đã lập bao nhiêu đơn đặt hàng
SELECT NV.MANHANVIEN,HO + ' ' + TEN AS HOTEN, COUNT(CTHD.SOHOADON) AS TONGDONDATHANG
   FROM NHANVIEN AS NV
     INNER JOIN DONDATHANG AS DDH
	    ON NV.MANHANVIEN = DDH.MANHANVIEN
		INNER JOIN CHITIETDATHANG AS CTHD
		   ON CTHD.SOHOADON = DDH.SOHOADON
GROUP BY NV.MANHANVIEN,HO,TEN