--5. 12 Trong đơn đặt hàng số 3 đặt mua những mặt hàng nào và số tiền mà khách hàng
--phải trả cho mỗi mặt hàng là bao nh iêu (số tiền phải trả được tính theo công thức
--SOLUONG×GIABAN - SOLUONG×GIABAN×MUCGIAMGIA/100)
SELECT DDH.SOHOADON,MH.MAHANG,TENHANG,KH.MAKHACHHANG,TENGIAODICH,(CTDH.SOLUONG * CTDH.GIABAN - CTDH.SOLUONG * CTDH.GIABAN * CTDH.MUCGIAMGIA / 100) AS N'SỐ TIỀN PHẢI TRẢ'
   FROM KHACHHANG AS KH 
     INNER JOIN DONDATHANG AS DDH 
	    ON KH.MAKHACHHANG = DDH.MAKHACHHANG
     INNER JOIN CHITIETDATHANG AS CTDH
	    ON DDH.SOHOADON = CTDH.SOHOADON
     INNER JOIN MATHANG AS MH
	    ON CTDH.MAHANG = MH.MAHANG
WHERE DDH.SOHOADON = 3
--5. 13 Hãy cho biết có những khách hàng nào lại chính là đối tác cung cấp hàng của
--công ty (tức là có cùng tên giao dịch).
SELECT KH.MAKHACHHANG,KH.TENGIAODICH,NCC.MACONGTY,NCC.TENCONGTY,NCC.TENGIAODICH,COUNT(NCC.MACONGTY)
    FROM KHACHHANG AS KH
	INNER JOIN DONDATHANG AS DDH
	       ON KH.MAKHACHHANG = DDH.MAKHACHHANG
    INNER JOIN CHITIETDATHANG AS CTHD
	       ON CTHD.SOHOADON = DDH.SOHOADON
	INNER JOIN MATHANG AS MH
	       ON CTHD.MAHANG = MH.MAHANG
    INNER JOIN NHACUNGCAP NCC
	       ON MH.MACONGTY = NCC.MACONGTY
GROUP BY KH.MAKHACHHANG,KH.TENGIAODICH,NCC.MACONGTY,NCC.TENCONGTY,NCC.TENGIAODICH
--5. 14 Trong công ty có những nhân viên nào có cùng ngày sinh?
SELECT MANHANVIEN,DAY(NGAYSINH) AS NGAYSINH,COUNT(NHANVIEN.MANHANVIEN) AS N'CÙNG NGÀY SINH'
    FROM NHANVIEN
GROUP BY MANHANVIEN,NGAYSINH;
--5. 15 Những đơn đặt hàng nào yêu cầu giao hàng ngay tại công ty đặt hàng và những
--đơn đó là của công ty nào?
SELECT DDH.SOHOADON, NOIGIAOHANG,KH.MAKHACHHANG,TENCONGTY,TENGIAODICH
   FROM DONDATHANG AS DDH
   INNER JOIN KHACHHANG AS KH
          ON DDH.MAKHACHHANG = KH.MAKHACHHANG

--5. 16 Cho biết tên công ty, tên giao dịch, địa chỉ và điện thoại của các khách hàng và
--các nhà cung cấp hàng cho công ty.
SELECT distinct KH.TENCONGTY,KH.TENGIAODICH,KH.DIACHI,KH.DIENTHOAI,NCC.MACONGTY,NCC.TENCONGTY,NCC.TENGIAODICH
   FROM KHACHHANG AS KH
   INNER JOIN DONDATHANG AS DDH
      ON KH.MAKHACHHANG = DDH.MAKHACHHANG
	  INNER JOIN CHITIETDATHANG AS CTHD
	      ON DDH.SOHOADON = CTHD.SOHOADON
		  INNER JOIN MATHANG AS MH
		  ON CTHD.MAHANG = MH.MAHANG
		    INNER JOIN NHACUNGCAP AS NCC
			   ON MH.MACONGTY = NCC.MACONGTY